export const searchTerms = [
  "Frontend Engineer",
  "Frontend Developer",
  "UI Developer",
  // "Web UI Developer",
  "JavaScript Developer",
  // "JavaScript Engineer",
  // "React Developer",
  // "React Engineer",
  "Web Developer",
  // "Web Engineer",
  // "Client-Side Developer",
  // "Client-Side Engineer",
  // "UX Engineer",
  // "User Experience Engineer",
  "HTML/CSS Developer",
  // "Full-Stack Developer",
  // "Full-Stack Engineer",
  // "Web Designer (with development skills)",
  "Interactive Developer",
]